# GotToVote Config

country: "Zambia"
election_year: "2016"

registration_end_date: "11th November 2015"

api_key: "AIzaSyAZrhdrNUIybMx92TGQKqlQRGIgCTb4ZnI"
table_id: "1UsF5ZHY6NO7luRGBsjJr44V0OeVdjM-xwu7BnpoM"

google_analytics: 'UA-36749298-3'

# ------------------------------------------------------------------------------
# Jekyll Config

# Handling Reading
safe: true

# Conversion
highlighter: pygments
